#! /bin/bash
first_print(){
echo `tput setaf 45`"
 ██████╗  ██████╗ ██╗    ██╗███████╗██████╗     ███████╗██╗   ██╗███████╗███████╗
 ██╔══██╗██╔═══██╗██║    ██║██╔════╝██╔══██╗    ██╔════╝██║   ██║██╔════╝██╔════╝
 ██████╔╝██║   ██║██║ █╗ ██║█████╗  ██████╔╝    █████╗  ██║   ██║█████╗  █████╗  
 ██╔═══╝ ██║   ██║██║███╗██║██╔══╝  ██╔══██╗    ██╔══╝  ██║   ██║██╔══╝  ██╔══╝  
 ██║     ╚██████╔╝╚███╔███╔╝███████╗██║  ██║    ██║     ╚██████╔╝██║     ██║     
 ╚═╝      ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝    ╚═╝      ╚═════╝ ╚═╝     ╚═╝     
  ________________________________________________________________________
 |                                                                        |
 |             	       WebSite: RedSecurity.xyz                           |
 |		        Creator: RedSecurity Admin			  |
 |		         E-mail: Info@RedSecurity.xyz			  |
 |									  | 
 --------------------------------------------------------------------------
"
}
scan(){
echo `tput setaf 249`
./apps/ffuf/ffuf -w $path -u $url/FUZZ -o ./default/result -of csv -mc all -t 30 -timeout 7 > /dev/null
echo `tput setaf  82`
printf P;sleep .12 ;printf l;sleep .12;printf e;sleep .12;printf a;sleep .12;printf s;sleep .12;printf e;sleep .12;printf " W";sleep .12;printf a;sleep .12;printf i;sleep .12;printf "t";sleep .2;printf " !";sleep .2; printf \!;sleep .2;printf "! \n"
echo `tput setaf 51`
res=`cat default/result | grep ,200,`

for i in $res
do
res2=`echo $i | cut -d ',' -f 5`
if [ "$res2" == 200 ]
then
echo $i | cut -d ',' -f 1 | sed "s@^@$url\/@" >> default/status_200
fi
done
cat default/result | cut -d ',' -f 3 | grep $url | sort | uniq -i >> ./default/status_300
cat default/status_300 | sed "s@$url\/@@"  > default/status_300_2
./apps/ffuf/ffuf -w default/status_300_2 -u $url/FUZZ -o ./default/status_300_ok -of csv -s -t 30 -mc all -timeout 7 > /dev/null
res3=`cat default/status_300_ok | grep ,200,`
for b in $res3
do
res4=`echo $b | cut -d ',' -f 5`
if [ "$res4" == 200 ]
then
echo $b | cut -d ',' -f 1 | sed "s@^@$url\/@" >> default/status_300_200
fi
done
cat default/status_300_ok | grep -v ,200, | cut -d ',' -f 3 | sort | uniq -i | sed "s@$url\/@@" > default/3000
./apps/ffuf/ffuf -w default/3000 -u $url/FUZZ -o ./default/3000_ok -of csv -s -mc 200 -t 30 -timeout 7 > /dev/null

if [ "$outputpath" == "SDDS" ]
then
(cat default/3000_ok | cut -d ',' -f 3 ; cat default/status_200 ; cat default/status_300_200) | sort | uniq -i | grep $url
else
otp_res=`(cat default/3000_ok | cut -d ',' -f 3 ; cat default/status_200 ; cat default/status_300_200) | sort | uniq -i | grep $url`
otp
echo "Result Saved in $outputpath.html"
fi
echo `tput setaf 10` "" `tput sgr0`
}
web_cat(){
web=`cat ./default/weburl | cut -d ',' -f 5 | grep 404`
}
web_cat2(){
web=`cat ./default/weburl | cut -d ',' -f 5 | grep 200`
}
otp(){
echo "" > default/otp
for o in $otp_res
do
echo \<td\>\<a href\=\"$o\"\>$o\<\/a\>\<\/td\> >> default/otp
done
echo '<html style="background-color: #00ccff"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta name="viewport"content="width=device-width, initial-scale=1, maximum-scale=1.0"/><title>Easy FFUF Report </title><link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet"/><link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"/><link rel="stylesheet"type="text/css"href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css"/><style>td{background-color: #cccccc;font-size: 2rem;  display: flex;justify-content: center}td:nth-child(even){background-color: #eeeeee;}</style></head><body><nav><div class="nav-wrapper"><p></p><ul id="nav-mobile" class="right hide-on-med-and-down"></ul></div></nav><main class="section no-pad-bot" id="index-banner"><div class="container"><br/><br/>
<h1 class="header center ">FFUF Report</h1><div class="row center"><pre>2020-11-09T06:10:50-05:00</pre><table id="ffufreport"><tbody>
<tr>' > $outputpath.html
cat default/otp >> $outputpath.html
echo '</tr>             
</tbody></table></div><br /><br /></div></main><script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script><script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script><script>$(document).ready(function(){$('#ffufreport').DataTable({"aLengthMenu":[[250, 500, 1000, 2500, -1],[250, 500, 1000, 2500, "All"]]})
        $('select').formSelect();});</script><style>body{display:flex;min-height:100vh;flex-direction:column;}main{flex: 1 0 auto;}</style></body></html>' >> $outputpath.html
}



#----------------------------------------functions()
echo "" > default/status_200
echo "" > default/status_300_200
echo "" > default/status_300
echo "" > default/3000
echo "" > default/result
echo "" > default/weburl
echo "" > default/testurl
echo "" > default/3000_ok
echo "" > default/otp
echo "" > default/status_300_2
echo "" > default/status_300_ok
echo "" > default/testurl2

outputpath="SDDS"
clear
first_print
echo `tput setaf 202`
sleep .12

read -p' ┌─[Please Enter Your URL]
 └──╼ ' url
if [ "$url" == "" ]
then
while [ 1 == 1 ]
do
read -p' ┌─[Please Enter Your URL]
 └──╼ ' url
if [ "$url" != "" ]
then
break
fi
done
fi
echo `tput setaf 197`

read -p' ┌─[Do You Want To use Default Word List? [Y]/N ]
 └──╼ ' yon
case $yon in
"Y") 
path="default/wordlist.txt"
;;
"y")
path="default/wordlist.txt"
;;
"N") 
echo `tput setaf 47`
read -p' ┌─[Please Enter Your Word List Path]
 └──╼ ' path
if [ "$path" == "" ]
then
while [ 1 == 1 ]
do
read -p' ┌─[Please Enter Your Word List Path]
 └──╼ ' path
if [ "$path" != "" ]
then
break
fi
done
fi
;;
"n")
echo `tput setaf 47`
read -p' ┌─[Please Enter Your Word List Path]
 └──╼ ' path
if [ "$path" == "" ]
then
while [ 1 == 1 ]
do
read -p' ┌─[Please Enter Your Word List Path]
 └──╼ ' path
if [ "$path" != "" ]
then
break
fi
done
fi
;;
"")
path="default/wordlist.txt"
;;
*) echo `tput setaf 160`
echo "Your Input is Invalid :)"
echo ""
sleep 1
exit;; 
esac
echo `tput setaf 131`
read -p' ┌─[Do You Want To Save Output? [N]/Y ]
 └──╼ ' output
case $output in
"N") ;;
"n") ;;
"Y")
echo `tput setaf 103`
read -p' ┌─[Enter Your Output File Path]
 └──╼ ' outputpath
if [ "$outputpath" == "" ]
then
while [ 1 == 1 ]
do
read -p' ┌─[Enter Your Output File Path]
 └──╼ ' outputpath
if [ "$outputpath" != "" ]
then
break
fi
done
fi
;;
"y")
echo `tput setaf 103`
read -p' ┌─[Enter Your Output File Path]
 └──╼ ' outputpath
if [ "$outputpath" == "" ]
then
while [ 1 == 1 ]
do
read -p' ┌─[Enter Your Output File Path]
 └──╼ ' outputpath
if [ "$outputpath" != "" ]
then
break
fi
done
fi

 ;;
"") ;;
*) echo `tput setaf 160`
echo "Your Input is Invalid :)"
echo ""
sleep 1
exit;; 
esac


url=`echo $url | sed 's/https:\/\///' | sed 's/http:\/\///' | sed 's/^/oupuput/' | sed 's/oupuputwww.//' | sed 's/oupuput//' | cut -d '/' -f 1`

web=`curl -I http://$url -s | head -1 | awk '{print $2}'`
if [ "$web" == 200 ]
then
url=http://$url
scan
exit
fi
web=`curl -I https://$url -s | head -1 | awk '{print $2}'`
if [ "$web" == 200 ]
then
url=https://$url
scan
exit
fi
web=`curl -I http://www.$url -s | head -1 | awk '{print $2}'`
if [ "$web" == 200 ]
then
url=http://www.$url
scan
exit
fi
web=`curl -I https://www.$url -s | head -1 | awk '{print $2}'`
if [ "$web" == 200 ]
then
url=https://www.$url
scan
exit
fi


echo "Sorry , Apparently your url is wrong :)"
